#Toggle oedldoedl series join messages. [Default: true]
join_messages = true

[Tooltips]

	[Tooltips.Origin]
		#Set color for origin annotations. [Default: GOLD]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		tooltip_annotation_formatting = "GOLD"
		#Toggle origin tooltips. [Default: true]
		enable_tooltip = true
		#Set color for origin tooltip. [Default: WHITE]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		text_formatting = "WHITE"
		#Toggle whether to display the keyboard key for origin tooltips. [Default: false]
		enable_hold_key = true

	[Tooltips.Effects]
		#Set color for negativ effect tooltip. [Default: RED]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		negative_effect_formatting = "RED"
		#Set color for effect annotations. [Default: GOLD]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		tooltip_annotation_formatting = "GOLD"
		#Set color for positive effect tooltip. [Default: GREEN]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		positive_effect_formatting = "GREEN"
		#Toggle effects tooltips. [Default: true]
		enable_tooltip = true
		#Set color for generel effect tooltip. [Default: AQUA]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		text_formatting = "AQUA"
		#Toggle whether to display the keyboard key for effects tooltips. [Default: false]
		enable_hold_key = true

	[Tooltips.Information]
		#Set color for information annotations. [Default: GOLD]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		tooltip_annotation_formatting = "GOLD"
		#Toggle information tooltips. [Default: false]
		enable_tooltip = false
		#Set color for information tooltip. [Default: WHITE]
		#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
		text_formatting = "WHITE"
		#Toggle information tooltips. [Default: true]
		enable_annotation = true
		#Toggle whether to display the keyboard key for information tooltips. [Default: false]
		enable_hold_key = true

[Integration]
	#Toggle JEI descriptions of vanilla items (added by this mod). [Default: true]
	jei_descriptions = true

