#Toggle all recipes from this mod. All recipes for items / blocks / liquids will be disabled. This option is intended for use in a modpack with custom recipes so you do not have to remove them with Crafttweaker. This can break certain recipes or other mechanics. [Default: true]
enable_mod_recipes = true

[Recipes]
	#Toggle additional recipes for uncraftable items. [Default: true]
	enable_additional_recipes = true
	#Toggle recipes to convert between storage blocks / block color variants etc. [Default: true]
	enable_conversion_recipes = true

[Content]
	#Toggle if the wrench is usable in survival mode. [Default: true]
	debug_wrench_useable_in_survival = true
	#Toggle if unobtainable vanilla items like command blocks and spawner should be added to a dedicated creative tab. This is especially useful when JEI is installed for easy viewing or quick cheating of items. [Default: true]
	unobtainable_items_in_creative_tab = true

[Properties]
	#Toggle whether items added by oedldoedl mods should have an enchantment effect (if present). [Default: true]
	enchantment_effects = true
	#Toggle whether blocks added by oedldoedl mods should drop experience. [Default: true]
	blocks_drop_experience = true
	#Toggle whether items added by oedldoedl mods should have immunity to fire effect (if present). [Default: true]
	fire_immunity = true
	#Toggle whether items added by oedldoedl mods should have custom colored rarities (if present). [Default: true]
	item_rarities = true

	[Properties.Durability]
		#Set shield durability multiplier. [Default: 3.0]
		#Range: 0.0 ~ 10.0
		shield_durability_multiplier = 3.0
		#Set shears durability multiplier. [Default: 0.94957983]
		#Range: 0.0 ~ 10.0
		shears_durability_multiplier = 0.94957983
		#Set paxel durability multiplier. [Default: 3.0]
		#Range: 0.0 ~ 10.0
		paxel_durability_multiplier = 3.0

