#Toggle all recipes from this mod. All recipes for items / blocks / liquids will be disabled. This option is intended for use in a modpack with custom recipes so you do not have to remove them with Crafttweaker. This can break certain recipes or other mechanics. [Default: true]
enable_mod_recipes = true

[Content]
	#Set the needle durability. [Default: 100]
	#Range: 0 ~ 10000
	needle_durability = 100

	[Content."Troll TNT"]
		#Toggle fire. [Default: false]
		cause_fire = false
		#Set explosion mode. [Default: DESTROY]
		#Allowed Values: NONE, BREAK, DESTROY
		explosion_mode = "DESTROY"
		#Toggle if troll tnt can be broken. [Default: true]
		multiply_on_break = true
		#Set the explosion strength. [Default: 3]
		#Range: 1 ~ 100
		explosion_strength = 3
		#Set fuse time (in ticks) (20 = 1sec). [Default: 5]
		#Range: 5 ~ 1200
		fuse_time = 5

	[Content.Staffs]
		#Toggle wand effects. [Default: true]
		enabled = true

		[Content.Staffs.Explosion]
			#Toggle fire. [Default: true]
			cause_fire = false
			#Set the cooldown (in ticks) (20 = 1sec). [Default: 80]
			#Range: 0 ~ 1200
			cooldown = 80
			#Set the range (in blocks) (high values may not work properly). [Default: 50]
			#Range: 1 ~ 100
			range = 50
			#Set explosion mode. [Default: DESTROY]
			#Allowed Values: NONE, BREAK, DESTROY
			explosion_mode = "DESTROY"
			#Set the explosion strength (high values may cause lag). [Default: 15]
			#Range: 0 ~ 100
			explosion_strength = 15

		[Content.Staffs.Lightning]
			#Set the cooldown (in ticks) (20 = 1sec). [Default: 30]
			#Range: 0 ~ 1200
			cooldown = 30
			#Set the range (in blocks) (high values may not work properly). [Default: 40]
			#Range: 1 ~ 100
			range = 40

	[Content."Equipment Sets"]
		#Toggle explosions from unstable equipment after dropping or hitting entities. [Default: true]
		unstable_equipment_explosions = true
		#Toggle potion effects. [Default: true]
		emerald_effects = true

		[Content."Equipment Sets".Nagatorium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: 650fc1]
			rgb_bar_color = "650fc1"

		[Content."Equipment Sets".Sakurajimarium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: 2a2929]
			rgb_bar_color = "2a2929"

		[Content."Equipment Sets".Infinity]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Toggle the ability to break unbreakable blocks with certain infity tools. [Default: true]
			can_break_unbreakable = true
			#Toggle armor invulnerability . [Default: true]
			invulnerability = true
			#Toggle infinity tools aoe. [Default: true]
			aoe_break = true

		[Content."Equipment Sets".Toujourium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: c0c0c0]
			rgb_bar_color = "c0c0c0"

		[Content."Equipment Sets".Himejimarium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: 232033]
			rgb_bar_color = "232033"

		[Content."Equipment Sets".Quartarium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: 0e5191]
			rgb_bar_color = "0e5191"

		[Content."Equipment Sets".Gremorium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: 990000]
			rgb_bar_color = "990000"

		[Content."Equipment Sets".Argentorium]
			#Toggle abilities like potion effects / step up etc. [Default: true]
			abilities = true
			#Set rgb durability bar color (in hex). [Default: fbd985]
			rgb_bar_color = "fbd985"

	[Content.Dynamite]
		#Set the explosion strength. [Default: 3]
		#Range: 1 ~ 50
		dynamite_strength = 3
		#Set the explosion strength. [Default: 6]
		#Range: 1 ~ 50
		charged_dynamite_strength = 6
		#Set the explosion strength. [Default: 4]
		#Range: 1 ~ 50
		combat_dynamite_strength = 4

	[Content."Admin Tools"]
		#Set the cooldown (in ticks) (20 = 1sec). [Default: 20]
		#Range: 0 ~ 1200
		admin_staff_cooldown = 20
		#Toggle the ability to switch gamemodes with admin staff. [Default: false]
		enable_admin_staff_gamemodes = false
		#Toggle admin tools. [Default: false]
		enable_admin_tools = false
		#Set the default kick resason message. [Default: You deserve it!]
		kick_stick_message = "You deserve it!"
		#Toggle gamemode chestplate. [Default: false]
		enable_gamemode_chestplate = false
		#Set the default ban resason message. [Default: You deserve it!]
		ban_hammer_message = "You deserve it!"

	[Content."Bedrock Breaker"]
		#Toggle effects when a block is broken. [Default: true]
		effects = true
		#Set the cooldown (in ticks) (20 = 1sec). [Default: 40]
		#Range: 0 ~ 1200
		cooldown = 40
		#Toggle bedrock breaker. [Default: true]
		enabled = true

